apiVersion: v1
kind: Pod
metadata:
  name: nodeapp-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: nodeapp
  containers:
    - name: nodeapp
      image: kammana/nodeapp:v1
      ports:
        - protocol: TCP
          port: 80
          targetPort: 80
